#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 94c6be0
#
# Source0 file verified with key 0xEBC80E415CA29677 (secure@wolfssl.com)
#
Name     : wolfssl
Version  : 5.7.6.stable
Release  : 2
URL      : https://github.com/wolfSSL/wolfssl/archive/v5.7.6-stable/wolfssl-5.7.6-stable.tar.gz
Source0  : https://github.com/wolfSSL/wolfssl/archive/v5.7.6-stable/wolfssl-5.7.6-stable.tar.gz
Source1  : https://github.com/wolfSSL/wolfssl/archive/v5.7.6-stable/wolfssl-5.7.6-stable.tar.gz.asc
Source2  : EBC80E415CA29677.pkey
Summary  : wolfssl C library.
Group    : Development/Tools
License  : GPL-2.0
Requires: wolfssl-license = %{version}-%{release}
Requires: wolfssl-plugins = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : gnupg
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
*** Description ***
The wolfSSL embedded SSL library (formerly CyaSSL) is a lightweight SSL/TLS
library written in ANSI C and targeted for embedded, RTOS, and
resource-constrained environments - primarily because of its small size, speed,
and feature set.  It is commonly used in standard operating environments as well
because of its royalty-free pricing and excellent cross platform support.
wolfSSL supports industry standards up to the current TLS 1.3 and DTLS 1.3
levels, is up to 20 times smaller than OpenSSL, and offers progressive ciphers
such as ChaCha20, Curve25519, and Blake2b. User benchmarking and feedback
reports dramatically better performance when using wolfSSL over OpenSSL.

%package dev
Summary: dev components for the wolfssl package.
Group: Development
Provides: wolfssl-devel = %{version}-%{release}
Requires: wolfssl = %{version}-%{release}

%description dev
dev components for the wolfssl package.


%package doc
Summary: doc components for the wolfssl package.
Group: Documentation

%description doc
doc components for the wolfssl package.


%package license
Summary: license components for the wolfssl package.
Group: Default

%description license
license components for the wolfssl package.


%package plugins
Summary: plugins components for the wolfssl package.
Group: Default

%description plugins
plugins components for the wolfssl package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) EBC80E415CA29677' gpg.status
%setup -q -n wolfssl-5.7.6-stable
cd %{_builddir}/wolfssl-5.7.6-stable

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738351032
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738351032
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wolfssl
cp %{_builddir}/wolfssl-5.7.6-stable/COPYING %{buildroot}/usr/share/package-licenses/wolfssl/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/wolfssl/callbacks.h
/usr/include/wolfssl/certs_test.h
/usr/include/wolfssl/crl.h
/usr/include/wolfssl/error-ssl.h
/usr/include/wolfssl/ocsp.h
/usr/include/wolfssl/openssl/aes.h
/usr/include/wolfssl/openssl/asn1.h
/usr/include/wolfssl/openssl/asn1t.h
/usr/include/wolfssl/openssl/bio.h
/usr/include/wolfssl/openssl/bn.h
/usr/include/wolfssl/openssl/buffer.h
/usr/include/wolfssl/openssl/camellia.h
/usr/include/wolfssl/openssl/cmac.h
/usr/include/wolfssl/openssl/cms.h
/usr/include/wolfssl/openssl/compat_types.h
/usr/include/wolfssl/openssl/conf.h
/usr/include/wolfssl/openssl/crypto.h
/usr/include/wolfssl/openssl/des.h
/usr/include/wolfssl/openssl/dh.h
/usr/include/wolfssl/openssl/dsa.h
/usr/include/wolfssl/openssl/ec.h
/usr/include/wolfssl/openssl/ec25519.h
/usr/include/wolfssl/openssl/ec448.h
/usr/include/wolfssl/openssl/ecdh.h
/usr/include/wolfssl/openssl/ecdsa.h
/usr/include/wolfssl/openssl/ed25519.h
/usr/include/wolfssl/openssl/ed448.h
/usr/include/wolfssl/openssl/engine.h
/usr/include/wolfssl/openssl/err.h
/usr/include/wolfssl/openssl/evp.h
/usr/include/wolfssl/openssl/fips_rand.h
/usr/include/wolfssl/openssl/hmac.h
/usr/include/wolfssl/openssl/kdf.h
/usr/include/wolfssl/openssl/lhash.h
/usr/include/wolfssl/openssl/md4.h
/usr/include/wolfssl/openssl/md5.h
/usr/include/wolfssl/openssl/modes.h
/usr/include/wolfssl/openssl/obj_mac.h
/usr/include/wolfssl/openssl/objects.h
/usr/include/wolfssl/openssl/ocsp.h
/usr/include/wolfssl/openssl/opensslconf.h
/usr/include/wolfssl/openssl/opensslv.h
/usr/include/wolfssl/openssl/ossl_typ.h
/usr/include/wolfssl/openssl/pem.h
/usr/include/wolfssl/openssl/pkcs12.h
/usr/include/wolfssl/openssl/pkcs7.h
/usr/include/wolfssl/openssl/rand.h
/usr/include/wolfssl/openssl/rc4.h
/usr/include/wolfssl/openssl/ripemd.h
/usr/include/wolfssl/openssl/rsa.h
/usr/include/wolfssl/openssl/safestack.h
/usr/include/wolfssl/openssl/sha.h
/usr/include/wolfssl/openssl/sha3.h
/usr/include/wolfssl/openssl/srp.h
/usr/include/wolfssl/openssl/ssl.h
/usr/include/wolfssl/openssl/ssl23.h
/usr/include/wolfssl/openssl/stack.h
/usr/include/wolfssl/openssl/tls1.h
/usr/include/wolfssl/openssl/txt_db.h
/usr/include/wolfssl/openssl/ui.h
/usr/include/wolfssl/openssl/x509.h
/usr/include/wolfssl/openssl/x509_vfy.h
/usr/include/wolfssl/openssl/x509v3.h
/usr/include/wolfssl/options.h
/usr/include/wolfssl/quic.h
/usr/include/wolfssl/sniffer.h
/usr/include/wolfssl/sniffer_error.h
/usr/include/wolfssl/ssl.h
/usr/include/wolfssl/test.h
/usr/include/wolfssl/version.h
/usr/include/wolfssl/wolfcrypt/aes.h
/usr/include/wolfssl/wolfcrypt/arc4.h
/usr/include/wolfssl/wolfcrypt/asn.h
/usr/include/wolfssl/wolfcrypt/asn_public.h
/usr/include/wolfssl/wolfcrypt/blake2-impl.h
/usr/include/wolfssl/wolfcrypt/blake2-int.h
/usr/include/wolfssl/wolfcrypt/blake2.h
/usr/include/wolfssl/wolfcrypt/camellia.h
/usr/include/wolfssl/wolfcrypt/chacha.h
/usr/include/wolfssl/wolfcrypt/chacha20_poly1305.h
/usr/include/wolfssl/wolfcrypt/cmac.h
/usr/include/wolfssl/wolfcrypt/coding.h
/usr/include/wolfssl/wolfcrypt/compress.h
/usr/include/wolfssl/wolfcrypt/cpuid.h
/usr/include/wolfssl/wolfcrypt/cryptocb.h
/usr/include/wolfssl/wolfcrypt/curve25519.h
/usr/include/wolfssl/wolfcrypt/curve448.h
/usr/include/wolfssl/wolfcrypt/des3.h
/usr/include/wolfssl/wolfcrypt/dh.h
/usr/include/wolfssl/wolfcrypt/dilithium.h
/usr/include/wolfssl/wolfcrypt/dsa.h
/usr/include/wolfssl/wolfcrypt/ecc.h
/usr/include/wolfssl/wolfcrypt/eccsi.h
/usr/include/wolfssl/wolfcrypt/ed25519.h
/usr/include/wolfssl/wolfcrypt/ed448.h
/usr/include/wolfssl/wolfcrypt/error-crypt.h
/usr/include/wolfssl/wolfcrypt/ext_kyber.h
/usr/include/wolfssl/wolfcrypt/ext_lms.h
/usr/include/wolfssl/wolfcrypt/ext_xmss.h
/usr/include/wolfssl/wolfcrypt/falcon.h
/usr/include/wolfssl/wolfcrypt/fe_448.h
/usr/include/wolfssl/wolfcrypt/fe_operations.h
/usr/include/wolfssl/wolfcrypt/fips_test.h
/usr/include/wolfssl/wolfcrypt/ge_448.h
/usr/include/wolfssl/wolfcrypt/ge_operations.h
/usr/include/wolfssl/wolfcrypt/hash.h
/usr/include/wolfssl/wolfcrypt/hmac.h
/usr/include/wolfssl/wolfcrypt/hpke.h
/usr/include/wolfssl/wolfcrypt/integer.h
/usr/include/wolfssl/wolfcrypt/kdf.h
/usr/include/wolfssl/wolfcrypt/kyber.h
/usr/include/wolfssl/wolfcrypt/lms.h
/usr/include/wolfssl/wolfcrypt/logging.h
/usr/include/wolfssl/wolfcrypt/md2.h
/usr/include/wolfssl/wolfcrypt/md4.h
/usr/include/wolfssl/wolfcrypt/md5.h
/usr/include/wolfssl/wolfcrypt/mem_track.h
/usr/include/wolfssl/wolfcrypt/memory.h
/usr/include/wolfssl/wolfcrypt/misc.h
/usr/include/wolfssl/wolfcrypt/mpi_class.h
/usr/include/wolfssl/wolfcrypt/mpi_superclass.h
/usr/include/wolfssl/wolfcrypt/pkcs12.h
/usr/include/wolfssl/wolfcrypt/pkcs7.h
/usr/include/wolfssl/wolfcrypt/poly1305.h
/usr/include/wolfssl/wolfcrypt/port/aria/aria-crypt.h
/usr/include/wolfssl/wolfcrypt/port/aria/aria-cryptocb.h
/usr/include/wolfssl/wolfcrypt/port/autosar/CryIf.h
/usr/include/wolfssl/wolfcrypt/port/autosar/Crypto.h
/usr/include/wolfssl/wolfcrypt/port/autosar/Csm.h
/usr/include/wolfssl/wolfcrypt/port/autosar/StandardTypes.h
/usr/include/wolfssl/wolfcrypt/port/liboqs/liboqs.h
/usr/include/wolfssl/wolfcrypt/port/maxim/max3266x-cryptocb.h
/usr/include/wolfssl/wolfcrypt/port/maxim/max3266x.h
/usr/include/wolfssl/wolfcrypt/port/maxim/maxq10xx.h
/usr/include/wolfssl/wolfcrypt/port/psa/psa.h
/usr/include/wolfssl/wolfcrypt/port/riscv/riscv-64-asm.h
/usr/include/wolfssl/wolfcrypt/port/rpi_pico/pico.h
/usr/include/wolfssl/wolfcrypt/pwdbased.h
/usr/include/wolfssl/wolfcrypt/random.h
/usr/include/wolfssl/wolfcrypt/rc2.h
/usr/include/wolfssl/wolfcrypt/ripemd.h
/usr/include/wolfssl/wolfcrypt/rsa.h
/usr/include/wolfssl/wolfcrypt/sakke.h
/usr/include/wolfssl/wolfcrypt/settings.h
/usr/include/wolfssl/wolfcrypt/sha.h
/usr/include/wolfssl/wolfcrypt/sha256.h
/usr/include/wolfssl/wolfcrypt/sha3.h
/usr/include/wolfssl/wolfcrypt/sha512.h
/usr/include/wolfssl/wolfcrypt/signature.h
/usr/include/wolfssl/wolfcrypt/siphash.h
/usr/include/wolfssl/wolfcrypt/sm2.h
/usr/include/wolfssl/wolfcrypt/sm3.h
/usr/include/wolfssl/wolfcrypt/sm4.h
/usr/include/wolfssl/wolfcrypt/sp_int.h
/usr/include/wolfssl/wolfcrypt/sphincs.h
/usr/include/wolfssl/wolfcrypt/srp.h
/usr/include/wolfssl/wolfcrypt/tfm.h
/usr/include/wolfssl/wolfcrypt/types.h
/usr/include/wolfssl/wolfcrypt/visibility.h
/usr/include/wolfssl/wolfcrypt/wc_encrypt.h
/usr/include/wolfssl/wolfcrypt/wc_kyber.h
/usr/include/wolfssl/wolfcrypt/wc_lms.h
/usr/include/wolfssl/wolfcrypt/wc_port.h
/usr/include/wolfssl/wolfcrypt/wc_xmss.h
/usr/include/wolfssl/wolfcrypt/wolfevent.h
/usr/include/wolfssl/wolfcrypt/wolfmath.h
/usr/include/wolfssl/wolfcrypt/xmss.h
/usr/include/wolfssl/wolfio.h
/usr/lib/libwolfssl.so
/usr/lib64/cmake/wolfssl/wolfssl-config-version.cmake
/usr/lib64/cmake/wolfssl/wolfssl-config.cmake
/usr/lib64/cmake/wolfssl/wolfssl-targets-relwithdebinfo.cmake
/usr/lib64/cmake/wolfssl/wolfssl-targets.cmake
/usr/lib64/pkgconfig/wolfssl.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/wolfssl/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wolfssl/4cc77b90af91e615a64ae04893fdffa7939db84c

%files plugins
%defattr(-,root,root,-)
/usr/lib/libwolfssl.so.43
/usr/lib/libwolfssl.so.43.0.0
